### ISSUE TITLE
Logo Sugestion

### ISSUE THREAD

**Issue by filipef101** [qwertydevelopment/aniuta#2]
Would it look better to have the logo including the "react" atom logo?
The witch one doesn't look the most professional imo.

Something like this maybe? Maybe without the middle witch?

![image](https://user-images.githubusercontent.com/18123246/92335179-9db20a00-f08c-11ea-9ae4-d2c5b42f8c0f.png)

**Comment by alexandrius** [comment]
The thing with witch and naming is quite deliberate. My wife is aniuta and we joke that she is a witch since she can predict weather 100% accuracy. Thanks for suggestion but will prefer not to change logo atm

**Comment by filipef101** [comment]
Cool, thanks for the explanation!
