### ISSUE TITLE
Only works with React Native typescript projects

### ISSUE THREAD

**Issue by filipef101** [qwertydevelopment/aniuta#3]
The typescript should be compiled to javascript when released to npm, with separated typings. Afaik this only works with react native because metro interprets Typescript

**Comment by filipef101** [comment]
Check for example the very similar package https://github.com/jamiebuilds/unstated-next

**Comment by alexandrius** [comment]
Thanks a lot. Will fix it tomorrow

**Comment by alexandrius** [comment]
Just checked works perfectly with javascript project.

**Comment by alexandrius** [comment]
@filipef101 Ok I think I know what was the issue. TypeScript was required dependency now it is not.
